import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "../public/css/main.css";
import "../public/css/bootstrap.css";
import "../public/css/style.css";
import "../public/css/responsive.css";
import "../public/css/font-awesome.css";
import "../public/css/animate.css";
import "../public/css/owl.css";
import "../public/css/swiper.css";
import "../public/css/flaticon.css";
import "../public/css/custom-animate.css";
import "../public/css/jquery-ui.css";
import "../public/css/animation.css";
import "../public/css/jquery.fancybox.min.css";
import "../public/css/jquery.mCustomScrollbar.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sampurna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"
/>
</head>

      <body className={inter.className}>
        {children}
        <Script src="/js/jquery.js" strategy="beforeInteractive" />
        <Script src="/js/popper.min.js" strategy="beforeInteractive" />
        <Script src="/js/bootstrap.min.js" strategy="beforeInteractive" />
        <Script src="/js/owl.js" />
        <Script src="/js/wow.js" />
        <Script src="/js/validate.js" />
        <Script src="/js/jquery.fancybox.js" />
        <Script src="/js/appear.js" />
        <Script src="/js/jquery.mCustomScrollbar.concat.min.js" />
        <Script src="/js/script.js" />
        <Script src="/js/swiper.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.js" />
      </body>
    </html>
  );
}
